#+LATEX_CLASS_OPTIONS: [a4paper,11pt]
#+OPTIONS: tags:t tasks:t text:t timestamp:nil toc:nil todo:t |:t num:nil date:nil
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}


#+TITLE: @@latex:\small{Astroparticle Physics}\\ \Large{Assignment-1 Answers}@@
#+AUTHOR: Varghese Reji

* Problem 1


We know that electron and positron have same mass. While happening pair production, a photon will annihilated and an electron and positron will  get created. The threshold for this will be the energy corresponding to mass of electron and positron. Since mass of both are same, we just need to take twice the mass of electron.

Mass of electron, $m_e=0.511MeV$.

So, the minimum threshold for pair production = $2m_e=1.022MeV$.

* Problem 2

The double differential charge current cross section for neutrino and antineutrino production on isoscalar nucleon targets is given by

\begin{equation*}
\frac{d^2 \sigma(\nu(\bar{\nu}) N)}{dx dQ^2} = \frac{G_F^2 M_W^4}{4\pi\left(Q^2+M_W^2\right)^2x}\sigma_r(\nu(\bar{\nu})N)
\end{equation*}

- $Q^2$: The invariant mass of the exchanged vector boson.
- $x$: which is Bjorken x, the fraction of the momentum of the incoming nucleon taken by the struck quark.
- $M_W$: Mass of nucleon.
- $\sigma_r(\nu (\bar{\nu}) N)$ : Reduced cross sections.

  $$\sigma_r (\nu N) = \left[Y_+F_2^{\nu}(x,Q^2)-y^2F_L^{\nu}(x,Q^2)+Y_-xF_3^{\nu}(x,Q^2) \right]$$
    $$\sigma_r(\bar{\nu} N) = \left[Y_+F_2^{\bar{\nu}}(x,Q^2) -y^2F_L^{\bar{\nu}}(x,Q^2) +Y_-xF_3^{\bar{\nu}}(x,Q^2)\right]$$

- $F_2, ~xF_3,~F_L$: These are functions related to quark momentum distributions

- $Y_{\pm} = 1\pm (1-y)^2$

- $y$: Measure of energy transfer between the lepton and hadron systems.

  
Most high energy physics experiments involve counting events and the rate at which the events are expected for an ideal measurement of a total cross-section $\sigma$ is given by the product $\mathcal{L}\times\sigma$ where $\mathcal{L}$ is the beam flux, which is the number of beam particles per second per unit target artea, or luminosity. In more detail, the double differential cross-section for deep inelastic scattering is related to N(x,Q^2), the number of events measured in the bin of size $\Delta x\Delta Q^2$ at $(x,Q^2)$, by

$$\Delta x\Delta Q^2 \frac{d^2 \sigma(\nu(\bar{\nu}) N)}{dx dQ^2} = \frac{N(x,Q^2)}{<\mathcal{L}>A(x,Q^2)}$$

- $\mathcal{L}$: Integrated luminosity
- $A(x,Q^2$: correction functions that accounts for finite resolution, efficiencies and acceptance.
