#+LATEX_CLASS_OPTIONS: [a4paper,11pt]
#+OPTIONS: tags:t tasks:t text:t timestamp:t toc:nil todo:t |:t num:nil date:nil
#+LATEX_HEADER: \usepackage[margin=1in]{geometry}
#+LATEX_HEADER: \usepackage{titlesec}
# #+LATEX_HEADER: \usepackage{subfigure}
#+LATEX_HEADER: \usepackage{caption}
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \usepackage{lipsum}

#+TITLE: Classical and Quantum Optics
#+SUBTITLE: Assignment-2 Answers
#+AUTHOR: Varghese Reji

* Problem 1

A beam with a photon flux of 1000 photons s^{-1} is incident on a detector with a quantum efficiency of 20%. If the time interval of the counter is set to 10s, calculate the average and standard deviation of the photocount number for the followin g scenarios:
- (a) :: the light has Poissonian statistics;
- (b) :: the light has super-Poissonian statistics with \Delta n=2\times \Delta n_{Poisson} ;
- (c) :: the light is in a photon number state.

** Answer
\phi = 1000/s, \eta=20%, t=10s

- (a) :: $\bar{n} = \frac{L \phi}{c}$

  But, $L=ct \Rightarrow \bar{n} = t \phi$

  Then, $\bar{n} = 10000$.$

  $\Delta n = \sqrt{n} = 100$

  The photocount number is given by, $$(\Delta N)^2 = \eta^2(\Delta n)^2 + \eta(1-\eta) \bar{n}$$

  $\Rightarrow$, $$\Delta N = 44.721$$.

  $$\bar{N} = \eta \bar{n} = 2000$$


- (b) :: Given $\Delta n = 2\times \Delta n_{Poisson}$.
  i.e., $\Delta n = 89.442$

  
  
  We know that, for super poissonian statistics,

  $$(\Delta n)^2 = \bar{n} + \bar{n}^2$$.

  $\Rightarrow$

  $$ \bar{n} + \bar{n}^2 = 4 \bar{n}_{Poiss}^2 = 8000$$

By solving this,

$$\bar{n} =88.944$$


$$\Delta N = 18.28, \bar{N} = 17.79$$

- (c) :: In phton number state, $\Delta n=0$. That means, there is no variation from mean value. Then, $\bar{n} = 10000$

$\Rightarrow$
$$\bar{N} = 2000, \Delta N = 40$$

* Problem 2
Calculate the values of g^{(2)}(0) for a monochromatic light wave with a square wave intensity modulation of \pm 20%.

* Problem 3
The 632.8 nm line of a neon discharge lamp is Doppler-broadened with a linewidth of 1.5GHz. Sketch the second-order correlation function g^{(2)}(\tau) for \tau in range 0-1 ns.

* Problem 4
For the coherent states |\alpha> with \alpha=5, calculate
- (a) :: the mean photon number;
- (b) :: the standard deviation in the photon number;
- (c) :: the quantum uncertinity in the optical phase.

* Problem 5
A ruby laser operating at 693 nm emits pulses of energy 1mJ. Calculate the quantum uncertinity in the phase of the laser light.

* Problem 6
For the coherent state |\alpha> with \alpha=|\alpha|e^{i\phi}, show that $<\alpha|\hat{X}_1|\alpha>=|\alpha|\cos\phi$ and $<\alpha|\hat{X}_2|\alpha>=|\alpha|\sin\phi$. Show further that $\Delta X_1 = \Delta X_2 = \frac{1}{2}$.

* Problem 7
Prove that for two coherent states |\alpha> and |\beta>,
$$|<\alpha|\beta>|^2=\exp(-|\alpha-\beta|^2)$$
